name: Backend CI/CD

on:
  push:
    paths:
      - 'backend/**'
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Force Load Secrets
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> $GITHUB_ENV
          echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}" >> $GITHUB_ENV
          echo "KUBE_CONFIG=${{ secrets.KUBE_CONFIG }}" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Build JAR
        run: |
          cd backend
          ./gradlew build -x test

      - name: Docker Login (manual)
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t $DOCKER_USERNAME/climbcommunity-backend:latest .

      - name: Push Docker Image
        run: |
          docker push $DOCKER_USERNAME/climbcommunity-backend:latest

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.29.0'

      - name: Deploy to K8s
        run: |
          echo "$KUBE_CONFIG" | base64 --decode > kubeconfig
          export KUBECONFIG=kubeconfig
          kubectl rollout restart deployment climbcommunity-backend-deployment
